Repository bonitasoft/bonita-documentation-site, pull requests merged in 2020-11, with the labels that each got.

#26 chore(gh-pages): prepare GitHub Pages push
  antora-playbook.yml
  package.json
Labels: enhancement

#44 Push to gh page on push
  .github/workflows/generate-documentation.yml
Labels: CI ⚙️, enhancement

#28 chore(license): add license to repository
  LICENSE
  package.json
Labels: documentation
