Repository bonitasoft/bonita-documentation-site, pull requests merged in 2021-03, with the labels that each got.

#159 feat: improve identification of preview environment and archive
  .github/workflows/generate-static-doc.yml
  .github/workflows/publish-pr-preview.yml
  README.adoc
  build-preview.bash
  scripts/generate-content-for-preview-antora-playbook.js
Labels: CI ⚙️

#176 chore: manage preview for the `labs` component that now replaces `bici`
  docs/migrate-from-old-documentation-site/migration-steps-put-the-site-live.adoc
  scripts/generate-content-for-preview-antora-playbook.js
Labels: CI ⚙️

#190 feat: improve archive component generation
  .github/workflows/generate-static-doc.yml
  antora-playbook.yml
  build-preview.bash
  resources/antora-ui-bundle.zip
  scripts/generate-content-for-preview-antora-playbook.js
Labels: enhancement

#193 chore: simplify the netlify deploys GitHub Workflow
  .github/workflows/generate-documentation.yml
Labels: CI ⚙️

#194 ci: upload documentation archive as gh release
  .github/workflows/generate-static-doc.yml
Labels: CI ⚙️

#187 chore: use ubuntu 20.04 in commit check gh wf
  .github/workflows/commit-message-check-format.yml
Labels: CI ⚙️

#173 doc: update the md to adoc conversion procedure
  docs/migrate-from-old-documentation-site/doc-content-conversion-from-md-to-adoc.adoc
Labels: documentation

#205 ci: Last update to go in production
  .github/workflows/generate-documentation.yml
  antora-playbook.yml
Labels: WIP

#197 doc: update after the rename of the 'bonitasoft.github.io' repository
  README.adoc
  docs/configure-netlify-redirects.adoc
  docs/migrate-from-old-documentation-site/doc-content-conversion-from-md-to-adoc.adoc
  docs/migrate-from-old-documentation-site/migration-steps-put-the-site-live.adoc
Labels: documentation

#218 chore: rename gh wf that publish to production
  .github/workflows/publish-production.yml
Labels: CI ⚙️

#224 feat: Add _getting Started redirect to tutorial-overview
  netlify.toml
Labels: SEO, enhancement
