Repository bonitasoft/bonita-documentation-site, pull requests merged in 2021-02, with the labels that each got.

#88 feat (bonita): Add 7.9 documentation contents
  antora-playbook.yml
Labels: :skull: To rebase

#98 chore(gh wf): store zipped artifact to speedup artifact operations
  .github/workflows/generate-documentation.yml
Labels: CI ⚙️

#102 chore: add action to use convential commits rules
  .github/workflows/commit-message-check-format.yml
  CONTRIBUTING.adoc
Labels: CI ⚙️, First Iteration, documentation

#105 chore: add a way to generate document content preview in PR
  .gitignore
  antora-playbook.yml
  build-preview.bash
  package.json
  scripts/generate-doc-content-pr-preview-antora-playbook.js
  scripts/generate-local-sources-antora-playbook.js
Labels: CI ⚙️

#82 doc: improve conversion procedure
  docs/migrate-from-old-documentation-site/doc-content-conversion-for-new-doc-site.adoc
Labels: documentation

#130 feat(Netlify): Add step in GH to deploy built site on Netlify
  .github/workflows/generate-documentation.yml
  netlify.toml
Labels: CI ⚙️

#128 chore: publish documentation site pr preview
  .github/workflows/publish-pr-preview.yml
  .gitignore
  antora-playbook.yml
  build-preview.bash
  scripts/generate-content-for-preview-antora-playbook.js
  scripts/generate-doc-content-pr-preview-antora-playbook.js
Labels: CI ⚙️, enhancement

#136 chore(netlify): set client timeout to 10 minutes
  .github/workflows/generate-documentation.yml
Labels: CI ⚙️

#150 feat: update the site url
  antora-playbook.yml
Labels: enhancement

#145 refactor: keep a single solution to manage preview
  .gitignore
  README.adoc
  build-preview.bash
  package.json
  scripts/generate-content-for-preview-antora-playbook.js
  scripts/generate-local-sources-antora-playbook.js
Labels: CI ⚙️

#146 chore: stop pushing to gh-pages
  .github/workflows/generate-documentation.yml
Labels: CI ⚙️
