Repository bonitasoft/bonita-documentation-site, pull requests merged in 2022-08, with the labels that each got.

#392 feat (release): Documentation site version updates
  antora-playbook.yml
  netlify.toml
Labels: D-day

#401 chore: update branches used to generate the PR preview
  .github/workflows/publish-pr-preview.yml
Labels: CI ⚙️

#404 refactor: reorganize Netlify redirects
  netlify.toml
Labels: production :skull_and_crossbones:

#406 chore(surge-preview-action): use the latest version of the surge-preview-tools action
  .github/actions/build-and-publish-pr-preview/action.yml
  .github/workflows/publish-pr-preview.yml
Labels: CI ⚙️

#408 docs: update the "archive a version" procedure
  docs/documentation-components-and-versions.adoc
Labels: documentation
