Repository bonitasoft/bonita-documentation-site, pull requests merged in 2022-01, with the labels that each got.

#285 chore: bump to node 16 and simplify github workflows
  .github/actions/build-setup/action.yml
  .github/workflows/generate-static-doc.yml
  .github/workflows/publish-pr-preview.yml
  .github/workflows/publish-production.yml
  .nvmrc
  README.adoc
  package-lock.json
Labels: CI ⚙️

#287 chore: add gh workflow to manage surge deployments
  .github/workflows/manage-surge-deployments.yml
Labels: CI ⚙️

#289 chore(wf): no checkout for PR convention checks
  .github/workflows/commit-message-check-format.yml
Labels: CI ⚙️

#288 doc: update netlify redirects information
  docs/configure-netlify-redirects.adoc
Labels: documentation

#286 chore: update git url to bonita-labs-doc
  README.adoc
  antora-playbook.yml
  docs/content/CONTRIBUTING.adoc
  docs/documentation-components-and-versions.adoc
  docs/migrate-from-old-documentation-site/doc-content-conversion-from-md-to-adoc.adoc
  scripts/generate-content-for-preview-antora-playbook.js
Labels: production :skull_and_crossbones:

#281 doc: improve tips about examples and attachments
  docs/content/CONTRIBUTING.adoc
Labels: documentation

#290 feat(ui): improve hover behavior
  resources/antora-ui-bundle.zip
Labels: Look&Feel

#284 doc: enhance the "troubleshooting" section
  docs/content/CONTRIBUTING.adoc
Labels: documentation

#293 feat(docPropagation): Create action to propagate doc
  .github/workflows/propagate-doc-upwards.yml
  README.adoc
  docs/documentation-components-and-versions.adoc
  scripts/propagate_doc_upwards.sh
Labels: CI ⚙️, doc-content

#295 chore: improve paths that trigger github workflows
  .github/workflows/publish-pr-preview.yml
  .github/workflows/publish-production.yml
Labels: CI ⚙️
