Repository bonitasoft/bonita-documentation-site, pull requests merged in 2022-11, with the labels that each got.

#468 ci: simplify artifact upload in "build-pr-site" action
  .github/actions/build-pr-site/action.yml
  .github/workflows/build-pr-site.yml
Labels: CI ⚙️

#469 ci: limit runs of the 'pr-title-check' workflow
  .github/workflows/commit-message-check-format.yml
Labels: CI ⚙️

#471 docs(contributing): make the alias examples consistent
  docs/content/CONTRIBUTING.adoc
Labels: documentation

#474 fix: Delete oldest comment and improve template
  .github/actions/build-and-publish-pr-preview/action.yml
  .github/actions/comment-pr-with-links/comments-with-url-links.js
  .github/actions/comment-pr-with-links/github.js
Labels: CI ⚙️, doc-content

#466 ci(preview-action): add ignore-errors input
  .github/actions/build-and-publish-pr-preview/action.yml
Labels: CI ⚙️

#478 ci: use bonitasoft/actions pr-title-conventional-commits
  .github/workflows/commit-message-check-format.yml
Labels: CI ⚙️
