Repository bonitasoft/bonita-documentation-site, pull requests merged in 2022-10, with the labels that each got.

#441 feat(release): remove the bonita 7.7 doc
  antora-playbook.yml
  netlify.toml
Labels: D-day, WIP

#446 chore: move special CI configuration out of the preview script
  .github/actions/build-and-publish-pr-preview/action.yml
  .github/actions/build-pr-site/action.yml
  .github/actions/build-setup/action.yml
  .github/workflows/generate-static-doc.yml
  .github/workflows/publish-pr-preview.yml
  .github/workflows/publish-production.yml
  README.adoc
  build-preview.bash
Labels: CI ⚙️

#447 ci: run all GitHub workflows on Ubuntu 22.04
  .github/workflows/build-pr-site.yml
  .github/workflows/commit-message-check-format.yml
  .github/workflows/generate-static-doc.yml
  .github/workflows/manage-surge-deployments.yml
  .github/workflows/propagate-doc-upwards.yml
  .github/workflows/publish-pr-preview.yml
  .github/workflows/publish-production.yml
  .github/workflows/teardown-inactive-surge-deployments.yml
  .github/workflows/update-theme-bundle.yml
Labels: CI ⚙️

#450 docs: improve the how-to about redirects/aliases
  docs/content/CONTRIBUTING.adoc
Labels: documentation

#459 ci: upload artifact when building PR site
  .github/actions/build-and-publish-pr-preview/action.yml
  .github/actions/build-pr-site/action.yml
  .github/actions/log-built-site-details/action.yml
  .github/actions/upload-pr-built-site-artifact/action.yml
  .github/workflows/build-pr-site.yml
  .github/workflows/publish-production.yml
Labels: CI ⚙️
