Repository bonitasoft/bonita-documentation-site, pull requests merged in 2023-05, with the labels that each got.

#558 feat: add option to display the search bar in the preview
  .github/workflows/publish-pr-preview.yml
  build-preview.bash
  scripts/generate-content-for-preview-antora-playbook.js
  test/documentation-content/bonita/v2022.1-beta/antora.yml
Labels: CI ⚙️

#520 feat: let Antora manage version aliases (latest & next)
  .github/actions/comment-pr-with-links/action.yml
  .github/actions/comment-pr-with-links/comments-with-url-links.js
  README.adoc
  antora-playbook.yml
  docs/configure-netlify-redirects.adoc
  lib/antora/versions-alias-extension.js
  lib/antora/versions-sorter-extension.js
  netlify.toml
  test/documentation-content/bonita/v2021.2/antora.yml
  test/documentation-content/bonita/v2022.2-alpha/antora.yml
  test/documentation-content/central/1.0/antora.yml
Labels: enhancement

#559 ci: use nvm.rc in GitHub Actions
  .github/actions/build-setup/action.yml
  .github/workflows/build-pr-site.yml
Labels: CI ⚙️

#573 ci(push-production): fix slack configuration
  .github/workflows/propagate-doc-upwards.yml
Labels: CI ⚙️

#553 docs: clean the documentation lifecyle page
  docs/documentation-components-and-versions.adoc
Labels: documentation
