Repository bonitasoft/bonita-documentation-site, pull requests merged in 2023-04, with the labels that each got.

#517 docs: improve the "contributors" documentation
  docs/content/CONTRIBUTING.adoc
  docs/documentation-components-and-versions.adoc
Labels: documentation

#545 ci: also publish preview with "test" documentation content
  .github/workflows/publish-pr-preview.yml
  antora-playbook.yml
  build-preview.bash
  scripts/generate-content-for-preview-antora-playbook.js
Labels: CI ⚙️

#549 feat: handle antora prerelease boolean attribute
  lib/antora/versions-sorter-extension.js
  scripts/generate-content-for-preview-antora-playbook.js
  test/documentation-content/bcd/4.0/antora.yml
  test/documentation-content/bcd/4.0/modules/ROOT/pages/index.adoc
  test/documentation-content/bcd/4.0/modules/ROOT/pages/page-01.adoc
  test/documentation-content/bcd/4.0/modules/ROOT/pages/page-02.adoc
  test/documentation-content/bcd/4.0/modules/ROOT/pages/page-03.adoc
  test/documentation-content/bcd/4.0/modules/ROOT/taxonomy.adoc
  test/documentation-content/bcd/4.1-alpha/antora.yml
  test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/index.adoc
  test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/page-01.adoc
  test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/page-02.adoc
  test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/page-03.adoc
  test/documentation-content/bcd/4.1-alpha/modules/ROOT/taxonomy.adoc
  test/documentation-content/bcd/4.2-alpha/antora.yml
  test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/index.adoc
  test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/page-01.adoc
  test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/page-02.adoc
  test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/page-03.adoc
  test/documentation-content/bcd/4.2-alpha/modules/ROOT/taxonomy.adoc
  test/documentation-content/central/1.0/antora.yml
  test/documentation-content/central/2.0/antora.yml
  test/documentation-content/central/2.0/modules/ROOT/pages/index.adoc
  test/documentation-content/central/2.0/modules/ROOT/pages/page-01.adoc
  test/documentation-content/central/2.0/modules/ROOT/taxonomy.adoc
Labels: enhancement
