Repository bonitasoft/bonita-documentation-site, pull requests merged in 2024-04, with the labels that each got.

#694 chore: make bonita 2022.1 an "out-of-support" version
  scripts/propagate_doc_upwards.bash
Labels: CI ⚙️

#697 ci: bump bonitasoft/actions from v2 to v3
  .github/actions/build-and-publish-pr-preview/action.yml
  .github/workflows/_reusable_pr-antora-content-guidelines-checker.yml
  .github/workflows/commit-message-check-format.yml
Labels: CI ⚙️

#699 ci: fix wrong action version in commit-message-check-format.yml
  .github/workflows/commit-message-check-format.yml
Labels: CI ⚙️

#698 ci: better support PR from fork for preview build and ref validation
  .github/actions/build-and-publish-pr-preview/README.md
  .github/actions/build-and-publish-pr-preview/action.yml
  .github/actions/build-pr-site/action.yml
  build-preview.bash
  lib/antora/log-aggregated-component-versions-extension.js
  scripts/generate-content-for-preview-antora-playbook.js
Labels: enhancement, CI ⚙️

#688 fix: remove the extra trailing slack in site.url
  antora-playbook.yml
Labels: bug

#701 ci: add reusable workflow for Surge
  .github/workflows/_reusable_surge-build-preview.yml
  .github/workflows/_reusable_surge-deploy-preview.yml
  .github/workflows/generate-static-doc.yml
  .github/workflows/publish-pr-preview.yml
  .github/workflows/surge-build-preview-site.yml
  .github/workflows/surge-build-preview-test.yml
  .github/workflows/surge-deploy-pr-preview.yml
Labels: github_actions

#702 ci: introduce 2 workflows to manage the PR deployments
  .github/workflows/surge-build-preview-site.yml
  .github/workflows/surge-build-preview-test.yml
  .github/workflows/surge-deploy-pr-preview-site.yml
  .github/workflows/surge-deploy-pr-preview-test.yml
Labels: CI ⚙️
